# Generated by Django 5.0.4 on 2024-04-23 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('civilID', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_student', models.BooleanField(default=False)),
                ('is_university', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UniversityUser',
            fields=[
                ('useraccount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('universityname', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('base.useraccount',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentemail', models.EmailField(blank=True, max_length=254, null=True)),
                ('fathernamearabic', models.CharField(blank=True, max_length=255, null=True)),
                ('familynamearabic', models.CharField(blank=True, max_length=255, null=True)),
                ('fathernameenglish', models.CharField(blank=True, max_length=255, null=True)),
                ('familynameenglish', models.CharField(blank=True, max_length=255, null=True)),
                ('nationality', models.CharField(blank=True, max_length=255, null=True)),
                ('StudentID', models.CharField(blank=True, max_length=255, null=True)),
                ('firstnamearabic', models.CharField(blank=True, max_length=255, null=True)),
                ('grandfathernamearabic', models.CharField(blank=True, max_length=255, null=True)),
                ('firstnameenglish', models.CharField(blank=True, max_length=255, null=True)),
                ('grandfathernameenglish', models.CharField(blank=True, max_length=255, null=True)),
                ('nationality1', models.CharField(blank=True, max_length=255, null=True)),
                ('phonenumber', models.CharField(blank=True, max_length=255, null=True)),
                ('malegender', models.BooleanField(blank=True, null=True)),
                ('femalegender', models.BooleanField(blank=True, null=True)),
                ('autism', models.BooleanField(blank=True, null=True)),
                ('Visualimpairment', models.BooleanField(blank=True, null=True)),
                ('learningdifficulties', models.BooleanField(blank=True, null=True)),
                ('psychological', models.BooleanField(blank=True, null=True)),
                ('Withoutdisabilit', models.BooleanField(blank=True, null=True)),
                ('Movementdisorder', models.BooleanField(blank=True, null=True)),
                ('CommunicationDisorders', models.BooleanField(blank=True, null=True)),
                ('Hearingimpairment', models.BooleanField(blank=True, null=True)),
                ('Physicalhealthdisability', models.BooleanField(blank=True, null=True)),
                ('Birtharea', models.CharField(blank=True, max_length=255, null=True)),
                ('Cityofbirth', models.CharField(blank=True, max_length=255, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('countryofbirth', models.CharField(blank=True, max_length=255, null=True)),
                ('no', models.BooleanField(blank=True, null=True)),
                ('yes', models.BooleanField(blank=True, null=True)),
                ('Jobtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('privatesector', models.BooleanField(blank=True, null=True)),
                ('governmentsector', models.BooleanField(blank=True, null=True)),
                ('jobstate', models.BooleanField(blank=True, null=True)),
                ('jobplace', models.CharField(blank=True, max_length=255, null=True)),
                ('relativerelation', models.CharField(blank=True, max_length=255, null=True)),
                ('phone1', models.CharField(blank=True, max_length=255, null=True)),
                ('fathersnameistriple', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('address1', models.CharField(blank=True, max_length=255, null=True)),
                ('Emergincypersonname', models.CharField(blank=True, max_length=255, null=True)),
                ('phone2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('yearofstudy', models.CharField(blank=True, max_length=255, null=True)),
                ('Cumulativeaverage', models.CharField(blank=True, max_length=255, null=True)),
                ('achievetest', models.CharField(blank=True, max_length=255, null=True)),
                ('area', models.CharField(blank=True, max_length=255, null=True)),
                ('school', models.CharField(blank=True, max_length=255, null=True)),
                ('highschooltype', models.CharField(blank=True, max_length=255, null=True)),
                ('cognitivetest', models.CharField(blank=True, max_length=255, null=True)),
                ('mentionit', models.CharField(blank=True, max_length=255, null=True)),
                ('certificate', models.CharField(blank=True, max_length=255, null=True)),
                ('college', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.BooleanField(blank=True, null=True)),
                ('gender_m', models.BooleanField(blank=True, null=True)),
                ('gender_f', models.BooleanField(blank=True, null=True)),
                ('universityname', models.CharField(blank=True, max_length=255, null=True)),
                ('userstudent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UniversityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciamain', models.CharField(blank=True, max_length=255, null=True)),
                ('about_university', models.TextField(blank=True, null=True)),
                ('score1', models.FloatField(blank=True, null=True)),
                ('score2', models.FloatField(blank=True, null=True)),
                ('score3', models.FloatField(blank=True, null=True)),
                ('score4', models.FloatField(blank=True, null=True)),
                ('score5', models.FloatField(blank=True, null=True)),
                ('score6', models.FloatField(blank=True, null=True)),
                ('specialization1', models.CharField(blank=True, max_length=255, null=True)),
                ('seats1', models.IntegerField(blank=True, null=True)),
                ('college1', models.CharField(blank=True, max_length=255, null=True)),
                ('acceptance_rate1', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
