# Generated by Django 5.0.3 on 2024-04-10 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_universityuser_universityname'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMoreInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentemail', models.EmailField(max_length=254, verbose_name='البريد الالكتروني')),
                ('fathernamearabic', models.CharField(max_length=255, verbose_name='اسم الاب بالعربيه')),
                ('familynamearabic', models.CharField(max_length=255, verbose_name='اسم العائله بالعربيه')),
                ('fathernameenglish', models.CharField(max_length=255, verbose_name='اسم الاب بالانجليزيه')),
                ('familynameenglish', models.CharField(max_length=255, verbose_name='اسم العائله بالانجليزيه')),
                ('nationality', models.CharField(max_length=255, verbose_name='دوله الجنسيه')),
                ('StudentID', models.CharField(max_length=255, verbose_name='رقم الهويه الوطنيه')),
                ('firstnamearabic', models.CharField(max_length=255, verbose_name='الاسم الاول بالعربيه')),
                ('grandfathernamearabic', models.CharField(max_length=255, verbose_name='اسم الجد بالعربيه')),
                ('firstnameenglish', models.CharField(max_length=255, verbose_name='الاسم الاول بالانجليزيه')),
                ('grandfathernameenglish', models.CharField(max_length=255, verbose_name='اسم الجد بالانجليزيه')),
                ('nationality1', models.CharField(max_length=255, verbose_name='الجنسيه')),
                ('phonenumber', models.CharField(max_length=255, verbose_name='رقم الجوال')),
                ('malegender', models.BooleanField(default=True, verbose_name='ذكر')),
                ('femalegender', models.BooleanField(default=False, verbose_name='انثى')),
                ('autism', models.BooleanField(default=False, verbose_name='اضطرابات التوحد')),
                ('Visualimpairment', models.BooleanField(default=False, verbose_name='اعاقه بصريه')),
                ('learningdifficulties', models.BooleanField(default=False, verbose_name='صعوبات التعلم')),
                ('psychological', models.BooleanField(default=False, verbose_name='اضطربات نفسيه')),
                ('Withoutdisabilit', models.BooleanField(default=False, verbose_name='بدون اعاقه')),
                ('Movementdisorder', models.BooleanField(default=False, verbose_name='اضطربات فدط الحدكه')),
                ('CommunicationDisorders', models.BooleanField(default=False, verbose_name='اضطربات التواصل')),
                ('Hearingimpairment', models.BooleanField(default=False, verbose_name='اعاقه سمعيه')),
                ('Physicalhealthdisability', models.BooleanField(default=False, verbose_name='اعاقه بدنيه وصحيه')),
                ('Birtharea', models.CharField(max_length=255, verbose_name='منطقه الميلاد')),
                ('Cityofbirth', models.CharField(max_length=255, verbose_name='محل الميلاد - المدينه')),
                ('birthdate', models.DateField(verbose_name='تاريخ الميلاد')),
                ('countryofbirth', models.CharField(max_length=255, verbose_name='محل الميلاد - الدوله')),
                ('sonOfmartyrs', models.BooleanField(default=False, verbose_name='هل انت ابن/ابنه احد شهداء الواجب')),
                ('Age', models.IntegerField(verbose_name='عمر المتقدم / المتقدمه')),
                ('Jobtitle', models.CharField(max_length=255, null=True, verbose_name='المسمي الوظيفي')),
                ('jobstate', models.CharField(max_length=255, null=True, verbose_name='الحاله الوظيفيه')),
                ('jobplace', models.CharField(max_length=255, null=True, verbose_name='جه العمل')),
                ('relativerelation', models.CharField(max_length=255, verbose_name='صله القرابه')),
                ('phone1', models.CharField(max_length=255, verbose_name='الجوال')),
                ('fathersnameistriple', models.CharField(max_length=255, verbose_name='اسم ولي الامر ثلاثي')),
                ('address', models.CharField(max_length=255, verbose_name='العنوان')),
                ('address1', models.CharField(max_length=255, verbose_name='العنوان')),
                ('Emergincypersonname', models.CharField(max_length=255, verbose_name='اسم شخص للطوارئ')),
                ('phone2', models.CharField(max_length=255, verbose_name='رقم الجوال')),
                ('city', models.CharField(max_length=255, verbose_name='المدينه')),
                ('yearofstudy', models.IntegerField(verbose_name='العام الدراسي')),
                ('Cumulativeaverage', models.FloatField(verbose_name='المعدل التداكمي للعام')),
                ('achievetest', models.FloatField(verbose_name='درجه اختبار التحصيلي')),
                ('area', models.CharField(max_length=255, verbose_name='المنطقه')),
                ('school', models.CharField(max_length=255, verbose_name='المدرسه')),
                ('highschooltype', models.CharField(max_length=255, verbose_name='نوع الثانويه العامه')),
                ('cognitivetest', models.FloatField(verbose_name='درجه اختبار القدرات')),
                ('mentionit', models.CharField(max_length=255, verbose_name='اذكرها')),
                ('certificate', models.CharField(max_length=255, verbose_name='اسم الشهاده')),
                ('college', models.CharField(max_length=255, verbose_name='الكليه')),
                ('gender', models.BooleanField(default=False, verbose_name='سبق ان التحقت بجامعه او كليه اخري')),
                ('gender_m', models.BooleanField(default=False, verbose_name='سبق ان حصلت علي شهاده جامعيه')),
                ('universityname', models.CharField(max_length=255, verbose_name='اسم الجامعه')),
                ('studentUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
