# Generated by Django 5.0.3 on 2024-04-13 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_studentmoreinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_email', models.EmailField(max_length=254)),
                ('about_university', models.TextField()),
                ('score1', models.FloatField()),
                ('score2', models.FloatField()),
                ('score3', models.FloatField()),
                ('score4', models.FloatField()),
                ('score5', models.FloatField()),
                ('score6', models.FloatField()),
                ('specialization1', models.CharField(max_length=255)),
                ('seats1', models.IntegerField()),
                ('college1', models.CharField(max_length=255)),
                ('acceptance_rate1', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.universityuser')),
            ],
        ),
    ]
