# Generated by Django 5.0.3 on 2024-04-18 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_universitydata_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentemail', models.EmailField(blank=True, max_length=254, null=True)),
                ('fathernamearabic', models.CharField(blank=True, max_length=255, null=True)),
                ('familynamearabic', models.CharField(blank=True, max_length=255, null=True)),
                ('fathernameenglish', models.CharField(blank=True, max_length=255, null=True)),
                ('familynameenglish', models.CharField(blank=True, max_length=255, null=True)),
                ('nationality', models.CharField(blank=True, max_length=255, null=True)),
                ('StudentID', models.CharField(blank=True, max_length=255, null=True)),
                ('firstnamearabic', models.CharField(blank=True, max_length=255, null=True)),
                ('grandfathernamearabic', models.CharField(blank=True, max_length=255, null=True)),
                ('firstnameenglish', models.CharField(blank=True, max_length=255, null=True)),
                ('grandfathernameenglish', models.CharField(blank=True, max_length=255, null=True)),
                ('nationality1', models.CharField(blank=True, max_length=255, null=True)),
                ('phonenumber', models.CharField(blank=True, max_length=255, null=True)),
                ('malegender', models.BooleanField(blank=True, null=True)),
                ('femalegender', models.BooleanField(blank=True, null=True)),
                ('autism', models.BooleanField(blank=True, null=True)),
                ('Visualimpairment', models.BooleanField(blank=True, null=True)),
                ('learningdifficulties', models.BooleanField(blank=True, null=True)),
                ('psychological', models.BooleanField(blank=True, null=True)),
                ('Withoutdisabilit', models.BooleanField(blank=True, null=True)),
                ('Movementdisorder', models.BooleanField(blank=True, null=True)),
                ('CommunicationDisorders', models.BooleanField(blank=True, null=True)),
                ('Hearingimpairment', models.BooleanField(blank=True, null=True)),
                ('Physicalhealthdisability', models.BooleanField(blank=True, null=True)),
                ('Birtharea', models.CharField(blank=True, max_length=255, null=True)),
                ('Cityofbirth', models.CharField(blank=True, max_length=255, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('countryofbirth', models.CharField(blank=True, max_length=255, null=True)),
                ('no', models.BooleanField(blank=True, null=True)),
                ('yes', models.BooleanField(blank=True, null=True)),
                ('Jobtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('privatesector', models.BooleanField(blank=True, null=True)),
                ('governmentsector', models.BooleanField(blank=True, null=True)),
                ('jobstate', models.BooleanField(blank=True, null=True)),
                ('jobplace', models.CharField(blank=True, max_length=255, null=True)),
                ('relativerelation', models.CharField(blank=True, max_length=255, null=True)),
                ('phone1', models.CharField(blank=True, max_length=255, null=True)),
                ('fathersnameistriple', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('address1', models.CharField(blank=True, max_length=255, null=True)),
                ('Emergincypersonname', models.CharField(blank=True, max_length=255, null=True)),
                ('phone2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('yearofstudy', models.CharField(blank=True, max_length=255, null=True)),
                ('Cumulativeaverage', models.CharField(blank=True, max_length=255, null=True)),
                ('achievetest', models.CharField(blank=True, max_length=255, null=True)),
                ('area', models.CharField(blank=True, max_length=255, null=True)),
                ('school', models.CharField(blank=True, max_length=255, null=True)),
                ('highschooltype', models.CharField(blank=True, max_length=255, null=True)),
                ('cognitivetest', models.CharField(blank=True, max_length=255, null=True)),
                ('mentionit', models.CharField(blank=True, max_length=255, null=True)),
                ('certificate', models.CharField(blank=True, max_length=255, null=True)),
                ('college', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.BooleanField(blank=True, null=True)),
                ('gender_m', models.BooleanField(blank=True, null=True)),
                ('gender_f', models.BooleanField(blank=True, null=True)),
                ('universityname', models.CharField(blank=True, max_length=255, null=True)),
                ('userstudent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='StudentMoreInfo',
        ),
    ]
