# Generated by Django 5.0.3 on 2024-04-18 23:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_student_delete_studentmoreinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birthdate',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
